### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by xPekeno** [Macxion/FM-bombcrypto-bot#1]
Boa  tarde, estou com um problema na multiconta. Ele não vai para as outras conta fica somente dando f5 na mesma.
E só está logando via login e senha. Quando você coloca a opção pela metamask ele fala que não achou janela e fecha o bot.

**Comment by Macxion** [comment]
@xPekeno boa noite, sobre a questão do f5, se ele não achar a imagem requerida em um tempo x configurado na variável **max_attempt_found_img**, ele vai reiniciar o processo, em qual etapa ele fica recarregando? Na aba da Metamask? Independente de onde for, siga as instruções descritas [aqui](https://github.com/Macxion/FM-bombcrypto-bot#limita%C3%A7%C3%B5es), se a variável threshold não funcionar, substitua a(s) imagen(s) que o bot não está encontrando
pela(s) mesma(s), mas na sua resolução, na pasta **pics**. Sobre ele dizer que não achou janela aberta, em qual browser vc está testando? Fiz testes aqui no Chrome, Edge, Firefox, Brave e o erro não ocorreu.
